---
kind: pipeline
name: dockerhub-build-trigger

platform:
  arch: amd64

steps:
- name: call webhook
  pull: always
  image: curlimages/curl:latest
  environment:
    ENDPOINT:
      from_secret: dockerhub_endpoint
  commands:
  - curl -s -X POST $ENDPOINT


---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  branch:
    - master
    - "release/*"
  event:
    - push
    - tag
  status:
    - success
    - failure

depends_on:
  - dockerhub-build-trigger

steps:
  - name: discord
    pull: always
    image: appleboy/drone-discord:1.2.4
    settings:
      message: "{{#success build.status}} ✅[Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.\nevent: **`{{build.event}}`**\n\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`\n```{{commit.message}}``` {{else}} ❌[Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}} on `{{commit.branch}}`:\n``` {{commit.message}} ``` {{/success}}\n"
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token

# ---
# kind: pipeline
# name: notifications
#
# platform:
  # os: linux
  # arch: amd64
#
# platform:
  # os: linux
  # arch: amd64
#
# clone:
  # disable: true
#
# steps:
# - name: discord
  # pull: always
  # image: curlimages/curl
  # environment:
    # webhook_id:
      # from_secret: discord_webhook_id
    # webhook_token:
      # from_secret: discord_webhook_token
  # commands:
  # - curl -sL -H "Content-Type:application/json" -X POST https://discordapp.com/api/webhooks/$webhook_id/$webhook_token -d '{"wait":false,"content":"drone","username":"","avatar_url":"","tts":false,"embeds":[{"title":":white_check_mark:Build ${DRONE_BUILD_NUMBER} of `${DRONE_REPO}` succeeded.","description":"event:**`${DRONE_BUILD_EVENT}`**\n\ncommit [`${DRONE_COMMIT_SHA}`](${DRONE_COMMIT_LINK}) on [`${DRONE_COMMIT_BRANCH}`](https://git.dotya.ml/${DRONE_REPO}/src/branch/${DRONE_COMMIT_BRANCH})\n${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR_NAME}\n\n[go to repo](https://${DRONE_SYSTEM_HOST}/${DRONE_REPO})","url":"https://${DRONE_SYSTEM_HOST}/${DRONE_REPO}/${DRONE_BUILD_NUMBER}","color":7506394,"footer":{"text":"drone discord webhook"},"author":{"name":"${DRONE_COMMIT_AUTHOR}","url":"https://git.dotya.ml/${DRONE_COMMIT_AUTHOR}","icon_url":""},"fields":null}]}'
  # - curl -sL -H "Content-Type:application/json" -X POST https://discordapp.com/api/webhooks/$webhook_id/$webhook_token -d '{"content":"Hello, World!","tts":false,"embed":{"title":"Hello, Embed!","description":"This is an embedded message."}}'
# trigger:
  # branch:
    # - master
    # - "release/*"
  # event:
    # - push
    # - tag
  # status:
    # - success
    # - failure
#
# depends_on:
  # - dockerhub-build-trigger


# ---
# kind: pipeline
# name: notifications-cronbuild
#
# platform:
  # os: linux
  # arch: amd64
#
# clone:
  # disable: true
#
# steps:
# - name: discord
  # pull: always
  # image: curlimages/curl
  # environment:
    # webhook_id:
      # from_secret: discord_webhook_hourly_id
    # webhook_token:
      # from_secret: discord_webhook_hourly_token
  # commands:
  # - curl -sL -H "Content-Type:application/json" -X POST https://discordapp.com/api/webhooks/$webhook_id/$webhook_token -d '{"wait":false,"content":"","username":"","avatar_url":"","tts":false,"embeds":[{"title":":white_check_mark:Hourly build \#${DRONE_BUILD_NUMBER} of `${DRONE_REPO}` succeeded.","description":"event:**`${DRONE_BUILD_EVENT}`**\n\ncommit [`${DRONE_COMMIT_SHA}`](${DRONE_COMMIT_LINK}) on [`${DRONE_COMMIT_BRANCH}`](https://git.dotya.ml/${DRONE_REPO}/src/branch/${DRONE_COMMIT_BRANCH})\n${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR_NAME}\n\n[go to repo](https://${DRONE_SYSTEM_HOST}/${DRONE_REPO})","url":"https://${DRONE_SYSTEM_HOST}/${DRONE_REPO}/${DRONE_BUILD_NUMBER}","color":7506394,"footer":{"text":"drone discord webhook"},"author":{"name":"${DRONE_COMMIT_AUTHOR}","url":"https://git.dotya.ml/${DRONE_COMMIT_AUTHOR}","icon_url":"https://git.dotya.ml/user/avatar/${DRONE_COMMIT_AUTHOR}/-1"},"fields":null}]}'
# trigger:
  # event:
    # - cron
  # cron:
    # - hourly
    # - hourly-build
  # status:
    # - success
    # - failure
#
# depends_on:
  # - dockerhub-build-trigger

---
kind: pipeline
name: notifications-cronbuild

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  event:
    - cron
  cron:
    - hourly
    - hourly-build
  status:
    - success
    - failure

depends_on:
  - dockerhub-build-trigger

steps:
  - name: discord
    pull: always
    image: appleboy/drone-discord:1.2.4
    settings:
      webhook_id:
        from_secret: discord_webhook_hourly_id
      webhook_token:
        from_secret: discord_webhook_hourly_token
