---
kind: pipeline
name: trigger dockerhub build

platform:
  arch: amd64

steps:
- name: call webhook
  pull: if-not-exists
  image: curlimages/curl
  environment:
    ENDPOINT:
      from_secret: dockerhub_endpoint
  commands:
  - curl -X POST $ENDPOINT
