---
kind: pipeline
name: dockerhub-build-trigger

platform:
  arch: amd64

steps:
- name: call webhook
  pull: always
  image: curlimages/curl
  environment:
    ENDPOINT:
      from_secret: dockerhub_endpoint
  commands:
  #- curl -s -X POST $ENDPOINT
  - echo $ENDPOINT


---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: curlimages/curl
  environment:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
  commands:
  - curl -s -L -H "Content-Type:application/json" -X POST https://discordapp.com/api/webhooks/$webhook_id/$webhook_token -d {"wait":false,"content":"","username":"","avatar_url":"","tts":false,"embeds":[{"title":":white_check_mark:Build \#${DRONE_BUILD_NUMBER} of `${DRONE_REPO}` succeeded.","description":"event:**`${DRONE_BUILD_EVENT}`**\n\ncommit [`${DRONE_COMMIT_SHA}`](${DRONE_COMMIT_LINK}) on [`${DRONE_COMMIT_BRANCH}`](https://git.dotya.ml/${DRONE_REPO}/src/branch/${DRONE_COMMIT_BRANCH})\n${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR_NAME}\n\n[go to repo](https://${DRONE_SYSTEM_HOST}/${DRONE_REPO})","url":"https://${DRONE_SYSTEM_HOST}/${DRONE_REPO}/${DRONE_BUILD_NUMBER}","color":7506394,"footer":{"text":"drone discord webhook"},"author":{"name":"${DRONE_COMMIT_AUTHOR}","url":"https://git.dotya.ml/${DRONE_COMMIT_AUTHOR}","icon_url":"https://git.dotya.ml/user/avatar/${DRONE_COMMIT_AUTHOR}/-1"},"fields":null}]}
trigger:
  branch:
    - master
    - "release/*"
  event:
    - push
    - tag
  status:
    - success
    - failure

depends_on:
  - dockerhub-build-trigger


---
kind: pipeline
name: notifications-cronbuild

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: curlimages/curl
  environment:
    webhook_id:
      from_secret: discord_webhook_hourly_id
    webhook_token:
      from_secret: discord_webhook_hourly_token
    ENDPOINT: https://discordapp.com/api
    #MESSAGE: "{ \"wait\": false, \"content\": \"\", \"username\": \"\", \"avatar_url\": \"\", \"tts\": false, \"embeds\": [ { \"title\": \":white_check_mark:  Build #${DRONE_BUILD_NUMBER} of `${DRONE_REPO}` succeeded.\", \"description\": \"event: **`${DRONE_BUILD_EVENT}`**\n\ncommit [`${DRONE_COMMIT_SHA:0:8}`](${DRONE_COMMIT_LINK}) on [`${DRONE_COMMIT_BRANCH}`](${DRONE_REPO_LINK}/src/branch/${DRONE_COMMIT_BRANCH})\n${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR_NAME}\n\n[go to repo](${DRONE_REPO})\", \"url\": \"https://${DRONE_SYSTEM_HOST}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}\", \"color\": 7506394, \"footer\": { \"text\": \"drone discord webhook\" }, \"author\": { \"name\": \"${DRONE_COMMIT_AUTHOR}\", \"url\": \"https://git.dotya.ml/${DRONE_COMMIT_AUTHOR}\", \"icon_url\": \"https://git.dotya.ml/user/avatar/${DRONE_COMMIT_AUTHOR}/-1\" }, \"fields\": null } ] }"
  commands:
  #- curl -H "Content-Type: application/json" -X POST $ENDPOINT/webhooks/$webhook_id/$webhook_token -d "{ \"wait\": false, \"content\": \"\", \"username\": \"\", \"avatar_url\": \"\", \"tts\": false, \"embeds\": [ { \"title\": \":white_check_mark:  Build #${DRONE_BUILD_NUMBER} of `${DRONE_REPO}` succeeded.\", \"description\": \"event: **`${DRONE_BUILD_EVENT}`**\n\ncommit [`${DRONE_COMMIT_SHA:0:8}`](${DRONE_COMMIT_LINK}) on [`${DRONE_COMMIT_BRANCH}`](${DRONE_REPO_LINK}/src/branch/${DRONE_COMMIT_BRANCH})\n${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR_NAME}\n\n[go to repo](${DRONE_REPO})\", \"url\": \"https://${DRONE_SYSTEM_HOST}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}\", \"color\": 7506394, \"footer\": { \"text\": \"drone discord webhook\" }, \"author\": { \"name\": \"${DRONE_COMMIT_AUTHOR}\", \"url\": \"https://git.dotya.ml/${DRONE_COMMIT_AUTHOR}\", \"icon_url\": \"https://git.dotya.ml/user/avatar/${DRONE_COMMIT_AUTHOR}/-1\" }, \"fields\": null } ] }"
  #- echo $ENDPOINT
  #- echo ${DRONE_COMMIT_SHA}
trigger:
  event:
    - cron
  cron:
    - hourly
    - hourly-build
  status:
    - success
    - failure

depends_on:
  - dockerhub-build-trigger
